# Generated by Django 3.1.7 on 2021-04-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210402_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='nothing.jpg', upload_to='posted_pics'),
        ),
    ]
