# Generated by Django 3.1.7 on 2021-04-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
