# Generated by Django 3.1.7 on 2021-04-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='contactno',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='area',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='region',
        ),
    ]
