# Generated by Django 3.1.7 on 2021-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_shippingaddress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
