# Generated by Django 3.1.7 on 2021-04-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shippingaddress_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
